version: "3"
services:
  - type: web
    name: appointy-backend
    env: node
    plan: starter
    buildCommand: "npm --prefix backend install"
    startCommand: "npm --prefix backend run start"
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: STRIPE_API_KEY
        sync: false
      - key: RAZORPAY_API_KEY
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: CLOUDINARY_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_SECRET_KEY
        sync: false
    healthcheckPath: "/test-db"
